name: digital_turbine_plugin
description: A new Flutter plugin for Digital Turbine SDK.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gaya.digital_turbine_plugin
        pluginClass: DigitalTurbinePlugin
      ios:
        pluginClass: DigitalTurbinePlugin